# Generated by Django 3.1.1 on 2021-01-06 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=70)),
                ('your_email', models.EmailField(max_length=254)),
                ('about_college', models.TextField()),
                ('your_branch', models.CharField(max_length=20)),
                ('faculty_name', models.CharField(max_length=50)),
                ('subj_teacher', models.CharField(max_length=50)),
                ('teaching_skill', models.CharField(max_length=10)),
                ('class_feedback', models.CharField(max_length=10)),
                ('after_class_feedback', models.CharField(max_length=10)),
                ('faculty_behaviour', models.CharField(max_length=10)),
                ('knowledge_about_subj', models.CharField(max_length=10)),
                ('Doubt_clearing', models.CharField(max_length=10)),
                ('your_suggestion', models.TextField()),
                ('feedback_date', models.DateTimeField(default=datetime.datetime(2021, 1, 6, 17, 12, 35, 251379, tzinfo=utc))),
            ],
        ),
    ]
